#define ERR_ERR "RUNTIME: "
#define ERR_RIGHT "EXPECTED RIGHT PARAM TO BE "
#define ERR_LEFT "EXPECTED LEFT PARAM TO BE "
#define ERR_WAS_EXPECTED "WAS EXPECTED TO BE "
#define ERR_OF_TYPE "OF TYPE "
#define ERR_RIGHT_TYPE ERR_ERR ERR_RIGHT ERR_OF_TYPE
#define ERR_LEFT_TYPE ERR_ERR ERR_LEFT ERR_OF_TYPE
#define ERR_STRING "STRING"
#define ERR_SCALAR "SCALAR"
#define ERR_ARRAY "ARRAY"
#define ERR_ARRAY_(X) "ARRAY[" #X "]"
#define ERR_BOOL "BOOL"
#define ERR_IF "IF"
#define ERR_CODE "CODE"
#define ERR_WHILE "WHILE"
#define ERR_FOR "FOR"

#define ERR_NOT_EMPTY "NOT EMPTY "

#define ERR_OR " OR "

#define ERR_SPECIAL_PRIVATE_1 ERR_ERR "RIGHT PARAMETER IS NOT STARTING WITH '_'"