# CMakeList.txt : CMake project for sqfvm, include source and define
# project specific logic here.
#
cmake_minimum_required(VERSION 3.18)

list(APPEND vm_headers_operators
        "${PROJECT_SOURCE_DIR}/src/operators/d_config.h"
        "${PROJECT_SOURCE_DIR}/src/operators/d_group.h"
        "${PROJECT_SOURCE_DIR}/src/operators/d_object.h"
        "${PROJECT_SOURCE_DIR}/src/operators/d_side.h"
        "${PROJECT_SOURCE_DIR}/src/operators/d_text.h"
        "${PROJECT_SOURCE_DIR}/src/operators/dlops.h"
        "${PROJECT_SOURCE_DIR}/src/operators/dlops_storage.h"
        "${PROJECT_SOURCE_DIR}/src/operators/group.h"
        "${PROJECT_SOURCE_DIR}/src/operators/object.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_config.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_diag.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_dummy_binary.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_dummy_nular.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_dummy_unary.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_generic.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_group.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_hashmap.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_logic.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_markers.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_math.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_namespace.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_object.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_osspecific.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_sqfvm.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_string.h"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_text.h")
list(APPEND vm_sources_operators
        "${PROJECT_SOURCE_DIR}/src/operators/dlops.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/group.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/object.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_config.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_diag.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_dummy_binary.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_dummy_nular.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_dummy_unary.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_generic.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_group.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_hashmap.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_logic.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_markers.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_math.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_namespace.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_object.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_osspecific.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_sqfvm.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_string.cpp"
        "${PROJECT_SOURCE_DIR}/src/operators/ops_text.cpp")
