[  ["assertEqual",     { compile "1+1+1" }, {1+1+1}],
   ["assertEqual",     { [1, 2, 3] apply { 0x1 } }, [1, 1, 1]],
   ["assertEqual",     { [] apply {+1} }, []],
   ["assertNil",       { comment "this is a comment" }],
   ["assertNil",       { nil }],
   ["assertTrue",      { true }],
   ["assertFalse",     { false }],
   ["assertTrue",      { 1 <= 1 }],
   ["assertEqual",     { str 0.5 }, "0.5"],
   ["assertEqual",     { toLower "UPPER" }, "upper"],
   ["assertEqual",     { toUpper "lower" }, "LOWER"],
   ["assertEqual",     { toArray "123" }, [49,50,51]],
   ["assertEqual",     { toString [49,50,51] }, "123"],
   ["assertEqual",     { ["1","2","3"] joinString "-"  }, "1-2-3"],
   ["assertEqual",     { [1,2,3] joinString "-"  }, "1-2-3"],
   ["assertEqual",     { "a"+"b"  }, "ab"],
   ["assert",          { nil isEqualTo nil }],
   ["assertFalse",     { [nil] isEqualTo [nil] }],
   ["assertTrue",      { isNil "_some_Non_Existing_Variable_"  }],
   ["assertFalse",     { private _var = 0; isNil "_var"  }],
   ["assertTrue",      { isNil { nil }  }],
   ["assertFalse",     { isNil { "a"+"b" }  }],
 //["assertEqual",     { for [{ _i = 0 }, { _i < 10 }, { _i = _i + 1 }] do { _i };  }, 10] //not implemented
   ["assertEqual",     { str (switch (true)) }, "true"]
]