[  ["assertTrue",      { [] in [[],1,2,3] }],
   ["assertFalse",     { [] in [] }],
   ["assertFalse",     { [] in [[123]] }],
   ["assertFalse",     { [] in [1] }],
   ["assertTrue",      { 1 in [1,2,3] }],
   ["assertFalse",     { 1 in [2,3,4] }],
   ["assertFalse",     { 1 in [[1]] }],
   ["assertFalse",     { 1 in [] }],
   ["assertTrue",      { false in [false] }],
   ["assertFalse",     { false in [true] }],
   ["assertFalse",     { false in [1,2,3] }],
   ["assertFalse",     { false in [[false]] }],
   ["assertFalse",     { false in [] }],
   ["assertTrue",      { "abc" in ["abc",1,2,3] }],
   ["assertFalse",     { "abc" in ["ABC",1,2,3] }],
   ["assertFalse",     { "abc" in ["",1,2,3] }],
   ["assertFalse",     { "abc" in [["abc"]] }],
   ["assertFalse",     { "abc" in [] }],
   ["assertTrue",      { player in [player, 1, 2, "", []] }],
   ["assertTrue",      { player in [objNull, player, 1, 2, "", []] }],
   ["assertTrue",      { player in [objNull, 1, 2, "", [], player] }],
   ["assertFalse",     { player in [objNull, 1, 2, "", []] }],
   ["assertFalse",     { player in ["",1,objNull,2,3] }],
   ["assertFalse",     { player in [[player]] }],
   ["assertFalse",     { player in [] }],
   ["assertTrue",      { "abc" in "abc" }],
   ["assertTrue",      { "abc" in "zzzabc" }],
   ["assertTrue",      { "abc" in "zzzabczzz" }],
   ["assertTrue",      { "abc" in "abczzz" }],
   ["assertFalse",     { "abc" in "ABC" }],
   ["assertFalse",     { "abc" in "zzzABC" }],
   ["assertFalse",     { "abc" in "zzzABCzzz" }],
   ["assertFalse",     { "abc" in "ABCzzz" }],
   ["assertFalse",     { "abc" in "" }]
]