[   ["assertTrue",      { true isEqualTo true }],
    ["assertFalse",     { true isEqualTo false }],
    ["assertFalse",     { false isEqualTo true }],
    ["assertTrue",      { false isEqualTo false }],
    ["assertFalse",     { 1 isEqualTo 2 }],
    ["assertFalse",     { 2 isEqualTo 1 }],
    ["assertTrue",      { 1 isEqualTo 1 }],
    ["assertTrue",      { [] isEqualTo [] }],
    ["assertTrue",      { [1] isEqualTo [1] }],
    ["assertTrue",      { [true] isEqualTo [true] }],
    ["assertFalse",     { [true] isEqualTo [false] }],
    ["assertFalse",     { [false] isEqualTo [true] }],
    ["assertTrue",      { [false] isEqualTo [false] }],
    ["assertTrue",      { [[1,2,3],[1,2,3]] isEqualTo [[1,2,3],[1,2,3]] }],
    ["assertFalse",     { [[1,2,3]] isEqualTo [[1,2,3],[1,2,3]] }],
    ["assertFalse",     { [nil] isEqualTo [nil] }],
    ["assertTrue",      { private _arr = [nil]; _arr isEqualTo _arr }],
    ["assertTrue",      { [player] isEqualTo [player] }],
    ["assertTrue",      { ["test"] isEqualTo ["test"] }],
    ["assertFalse",     { ["test"] isEqualTo ["TEST"] }]
]