[   ["assertTrue",      { true isEqualType true }],
    ["assertTrue",      { true isEqualType false }],
    ["assertTrue",      { false isEqualType true }],
    ["assertTrue",      { false isEqualType false }],
    ["assertTrue",      { 1 isEqualType 2 }],
    ["assertTrue",      { 2 isEqualType 1 }],
    ["assertTrue",      { 1 isEqualType 1 }],
    ["assertTrue",      { [] isEqualType [] }],
    ["assertTrue",      { [1] isEqualType [1] }],
    ["assertTrue",      { [true] isEqualType [true] }],
    ["assertTrue",      { [true] isEqualType [false] }],
    ["assertTrue",      { [false] isEqualType [true] }],
    ["assertTrue",      { [false] isEqualType [false] }],
    ["assertTrue",      { [[1,2,3],[1,2,3]] isEqualType [[1,2,3],[1,2,3]] }],
    ["assertTrue",      { [[1,2,3]] isEqualType [[1,2,3],[1,2,3]] }],
    ["assertTrue",      { [nil] isEqualType [nil] }],
    ["assertTrue",      { private _arr = [nil]; _arr isEqualType _arr }],
    ["assertTrue",      { [player] isEqualType [player] }],
    ["assertTrue",      { ["test"] isEqualType ["test"] }],
    ["assertTrue",      { ["test"] isEqualType ["TEST"] }],

    ["assertFalse",     { [] isEqualTypeAll "" }],
    ["assertFalse",     { [] isEqualTypeAll 1 }],
    ["assertFalse",     { [] isEqualTypeAll player }],
    ["assertFalse",     { [] isEqualTypeAll true }],
    ["assertTrue",      { ["1"] isEqualTypeAll "2" }],
    ["assertFalse",     { ["1", 2] isEqualTypeAll "3" }],
    ["assertTrue",      { [1] isEqualTypeAll 2 }],
    ["assertFalse",     { [1, "2"] isEqualTypeAll 3 }],
    ["assertTrue",      { [player] isEqualTypeAll player }],
    ["assertFalse",     { [player, "player"] isEqualTypeAll player }],
    ["assertTrue",      { [true] isEqualTypeAll false }],
    ["assertFalse",     { [true, "true"] isEqualTypeAll false }],

    ["assertFalse",     { "" isEqualTypeAny [] }],
    ["assertFalse",     { 1 isEqualTypeAny [] }],
    ["assertFalse",     { player isEqualTypeAny [] }],
    ["assertFalse",     { true isEqualTypeAny [] }],
    ["assertTrue",      { "1" isEqualTypeAny ["2"] }],
    ["assertTrue",      { "1" isEqualTypeAny ["2", 3] }],
    ["assertTrue",      { 1 isEqualTypeAny [2] }],
    ["assertTrue",      { 1 isEqualTypeAny [2, "3"] }],
    ["assertTrue",      { player isEqualTypeAny [player] }],
    ["assertTrue",      { player isEqualTypeAny [player, "player"] }],
    ["assertTrue",      { true isEqualTypeAny [false] }],
    ["assertTrue",      { true isEqualTypeAny [false, "true"] }],

    ["assertTrue",      { [] isEqualTypeArray [] }],
    ["assertTrue",      { ["1"] isEqualTypeArray ["2"] }],
    ["assertFalse",     { ["1"] isEqualTypeArray [] }],
    ["assertFalse",     { ["1"] isEqualTypeArray ["2", "3"] }],
    ["assertTrue",      { [1] isEqualTypeArray [2] }],
    ["assertFalse",     { [1] isEqualTypeArray [] }],
    ["assertFalse",     { [1] isEqualTypeArray [2, 3] }],
    ["assertTrue",      { [player] isEqualTypeArray [player] }],
    ["assertFalse",     { [player] isEqualTypeArray [] }],
    ["assertTrue",      { [true] isEqualTypeArray [false] }],
    ["assertFalse",     { [true] isEqualTypeArray [] }],
    ["assertFalse",     { [true] isEqualTypeArray [false, true] }],

    ["assertTrue",      { [] isEqualTypeParams [] }],
    ["assertFalse",     { [] isEqualTypeParams [nil] }],
    ["assertTrue",      { [nil] isEqualTypeParams [] }],
    ["assertTrue",      { [nil] isEqualTypeParams [nil] }],
    ["assertFalse",     { 1 isEqualTypeParams [2] }],
    ["assertTrue",      { [1] isEqualTypeParams [2] }],
    ["assertTrue",      { [1, 2] isEqualTypeParams [3] }],
    ["assertTrue",      { [1, 2] isEqualTypeParams [3, 4] }],
    ["assertFalse",     { [1, 2] isEqualTypeParams [3, "4"] }],
    // From Biki
    ["assertTrue",      { [1, 2, player, "10"] isEqualTypeParams [0, 0, objNull, ""] }],
    ["assertFalse",     { 123 isEqualTypeParams [0, 0, objNull, ""] }],
    ["assertFalse",     { [] isEqualTypeParams [0, 0, objNull, ""] }],
    ["assertFalse",     { [1, 2,player] isEqualTypeParams [0, 0, objNull, ""] }],
    ["assertTrue",      { [1, 2, player, "10", true] isEqualTypeParams [0, 0, nil, ""] }],
    ["assertTrue",      { [1, 2, getPos player, "10", true] isEqualTypeParams [0, 0, nil, ""] }]
]
