[   ["assertFalse",    { true isNotEqualTo true }],
    ["assertTrue",     { true isNotEqualTo false }],
    ["assertTrue",     { false isNotEqualTo true }],
    ["assertFalse",    { false isNotEqualTo false }],
    ["assertTrue",     { 1 isNotEqualTo 2 }],
    ["assertTrue",     { 2 isNotEqualTo 1 }],
    ["assertFalse",    { 1 isNotEqualTo 1 }],
    ["assertFalse",    { [] isNotEqualTo [] }],
    ["assertFalse",    { [1] isNotEqualTo [1] }],
    ["assertFalse",    { [true] isNotEqualTo [true] }],
    ["assertTrue",     { [true] isNotEqualTo [false] }],
    ["assertTrue",     { [false] isNotEqualTo [true] }],
    ["assertFalse",    { [false] isNotEqualTo [false] }],
    ["assertFalse",    { [[1,2,3],[1,2,3]] isNotEqualTo [[1,2,3],[1,2,3]] }],
    ["assertTrue",     { [[1,2,3]] isNotEqualTo [[1,2,3],[1,2,3]] }],
    ["assertTrue",     { [nil] isNotEqualTo [nil] }],
    ["assertFalse",    { private _arr = [nil]; _arr isNotEqualTo _arr }],
    ["assertFalse",    { [player] isNotEqualTo [player] }],
    ["assertFalse",    { ["test"] isNotEqualTo ["test"] }],
    ["assertTrue",     { ["test"] isNotEqualTo ["TEST"] }]
]